### ISSUE TITLE
Skips some steps on very slow rotation - fix

### ISSUE THREAD

**Issue by anythingwithawire** [Erriez/ErriezArduinoLibrariesAndSketches#1]
I found that putting a capacitor to ground from each of the encoder inputs would mean that when turning very slowly every "click" was picked up as a change of value, otherwise sometimes it would miss the odd click.

Value I used was ceramic 223, 22000 pf or also known as 0.022uF.

**Comment by Erriez** [comment]
Thanks for your feedback. Correct: Some rotary encoders may generate noise on the encoder pins caused by the sliding contacts. In this case adding a small capacitor is the best workaround.

I assume this issue can be closed, otherwise let me know. Have a nice day.
